apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployments
  labels:
    app: {{ .Release.Name }}-deployments
  annotations:
    app.gitlab.com/app: {{ .Values.deployment.gitlab.app }}
    app.gitlab.com/env: {{ .Values.deployment.gitlab.env }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Release.Name }}-deployments
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-deployments
    spec:
      containers:
      - name: {{ .Release.Name }}-deployments
        image: registry.gitlab.com/iswapi/user:{{ .Values.image.tag }}
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"