image: node:latest

stages:
  - build
  - dockerbuild
  - deploy

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

dockerbuild:
  stage: dockerbuild
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}
  only:
    - Kubernetes
    - main
deploy:
  image: dtzar/helm-kubectl
  stage: deploy
  script:
    -  helm upgrade user ./.helm --install --namespace $KUBE_NAMESPACE --create-namespace
      --set deployment.gitlab.app=${CI_PROJECT_PATH_SLUG}
      --set deployment.gitlab.env=${CI_ENVIRONMENT_SLUG}
      --set image.tag=${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}
  environment:
    name: $CI_COMMIT_BRANCH
  only:
    - Kubernetes
    - main